name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install ingestion deps
        run: pip install rdflib pyshacl
      - name: Install service deps
        run: pip install fastapi "uvicorn[standard]" SPARQLWrapper
      - name: Lint
        run: |
          pip install flake8
          flake8 earCrawler/core/crawler.py earCrawler/service/sparql_service.py
      - name: Run pytest
        run: pytest --maxfail=1 --disable-warnings
      - name: Run ingest tests
        run: python -m pytest tests/ingestion
      - name: Run service tests
        run: python -m pytest tests/service
