name: CI

on:
  push:
    branches: ['**']
    tags: ['v*']
  pull_request:

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install ingestion deps
        run: pip install rdflib pyshacl
      - name: Install service deps
        run: pip install fastapi "uvicorn[standard]" SPARQLWrapper
      - name: Install analytics deps
        run: pip install SPARQLWrapper
      - name: Install CLI deps
        run: pip install click requests tabulate
      - name: Install RAG deps
        run: pip install sentence-transformers faiss-cpu
      - name: Install KG service deps
        run: pip install fastapi SPARQLWrapper pyshacl
      - name: Install model deps
        run: pip install torch transformers peft accelerate bitsandbytes
      - name: Train Legal-BERT
        run: python earCrawler/models/legalbert/train.py --do_train --do_eval
      - name: Lint
        run: |
          pip install flake8
          flake8 earCrawler/core/crawler.py earCrawler/service/sparql_service.py
      - name: Lint KG service
        run: python -m flake8 earCrawler/service/kg_service.py
      - name: Lint analytics
        run: python -m flake8 earCrawler/analytics
      - name: Lint RAG code
        run: python -m flake8 earCrawler/rag
      - name: Lint CLI
        run: python -m flake8 earCrawler/cli/reports_cli.py
      - name: Run pytest
        run: pytest --maxfail=1 --disable-warnings
      - name: Run ingest tests
        run: python -m pytest tests/ingestion
      - name: Run service tests
        run: python -m pytest tests/service/test_sparql_service.py
      - name: Run KG service tests
        run: python -m pytest tests/service/test_kg_service.py
      - name: Run analytics tests
        run: python -m pytest tests/analytics
      - name: Run RAG tests
        run: python -m pytest tests/rag
      - name: Run agent tests
        run: python -m pytest tests/agent
      - name: Run CLI tests
        run: python -m pytest tests/cli/test_reports_cli.py
      - name: Install benchmark deps
        run: pip install sentence-transformers faiss-cpu peft bitsandbytes
      - name: Run benchmark script
        run: python scripts/benchmark.py --queries scripts/benchmark_queries.json

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build-and-test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build API image
        run: docker build -f docker/api.Dockerfile -t ghcr.io/${{ github.repository }}/api:${{ github.ref_name }} .
      - name: Push API image
        run: docker push ghcr.io/${{ github.repository }}/api:${{ github.ref_name }}
      - name: Build RAG image
        run: docker build -f docker/rag.Dockerfile -t ghcr.io/${{ github.repository }}/rag:${{ github.ref_name }} .
      - name: Push RAG image
        run: docker push ghcr.io/${{ github.repository }}/rag:${{ github.ref_name }}
      - name: Build agent image
        run: docker build -f docker/mistral.Dockerfile -t ghcr.io/${{ github.repository }}/agent:${{ github.ref_name }} .
      - name: Push agent image
        run: docker push ghcr.io/${{ github.repository }}/agent:${{ github.ref_name }}
      - name: Run monitor against staging
        shell: pwsh
        run: ./monitor.ps1 -Services @('https://staging/api/health','https://staging/kg/health','https://staging/agent/health')
